### ISSUE TITLE
Copy error on Tari Lesson 2

### ISSUE THREAD

**Issue by karbonbased** [tari-project/tari-dot-com-old#58]
https://www.tari.com/lessons/02_how_tari_works.html

is missing copy that's on https://github.com/tari-project/tari-dot-com/blob/main/_lessons/02_how_tari_works.md

See attached last sentence
![photo_2021-02-08_10-50-20](https://user-images.githubusercontent.com/16564599/107253765-45e14b80-69fc-11eb-8bfe-8040ea91f32e.jpg)

**Comment by delta1** [comment]
It looks like this is happening with most of the footnote copy
