### ISSUE TITLE
create an RSS feed for updates 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari-dot-com-old#84]
a useful suggestion 

https://www.reddit.com/r/tari/comments/pf7wtq/is_there_a_feed_url_for_tari_updates/

**Comment by CjS77** [comment]
Fixed in #86

**Comment by crocket** [comment]
Is there an RSS icon? People should be able to find the icon.

I found a little issue. The URLs from the feed have an extra slash.

> https://www.tari.com//updates/2021-09-28-update-61.html

**Comment by delta1** [comment]
Thanks @crocket nice suggestion
